run:
  go: "1.26"
  timeout: 5m

issues:
  exclude-dirs:
    - node_modules
    - .git

linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - ineffassign
    - staticcheck
    - unused
